---
- name: install httpd
  hosts: all
  tasks:
    - name: install http and register
      yum: 
        name: httpd
        state: installed
      register: install_result

    - debug: var=install_result 

