---
- name: Create user accounts for all our services
  hosts: all
  vars_files:
    - secret.yml 
  tasks:
    - name: Creating user from secret.yml
      user:
        name: "{{ username }}"
        password: "{{ passwd }}"


